#+title: An Analysis of Loanable Funds
#+author: Matt Brigida, Ph.D.
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+HTML_HEAD: <style>pre.src{background:#343131;color:white;} </style>
#+PROPERTY: header-args
#+bibliography: references.bib


#+begin_export html
<head>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});

      
      google.charts.setOnLoadCallback(drawChart);

      google.charts.setOnLoadCallback(drawChart2);
      google.charts.setOnLoadCallback(drawChart3);
      google.charts.setOnLoadCallback(drawChart4);
      google.charts.setOnLoadCallback(drawChartVert);


// supply loanable funds
      
      function drawChart3() {
        var data = google.visualization.arrayToDataTable([
          ['Quantity', 'Supply'],
          ['500',       2],
          ['600',       3],
          ['700',       4],
          ['800',       5]
        ]);

        var options = {
          title: '%',
          curveType: 'function',
          legend: { position: 'bottom' },
	    colors: ['#ff0000'],
        };

        var chart = new google.visualization.LineChart(document.getElementById('curve_chart3'));

        chart.draw(data, options);
      }

// demand loanable funds
      
      function drawChart4() {
        var data = google.visualization.arrayToDataTable([
          ['Quantity', 'Demand'],
          ['500',      5],
          ['600',      4],
          ['700',      3],
          ['800',      2]
        ]);

        var options = {
          title: '%',
          curveType: 'function',
          legend: { position: 'bottom' },
	    colors: ['#0000FF'],
        };

        var chart = new google.visualization.LineChart(document.getElementById('curve_chart4'));

        chart.draw(data, options);
      }

      // govt demand loanable funds verticle
      
      function drawChartVert() {
        var data = google.visualization.arrayToDataTable([
          ['Quantity', 'Demand'],
          ['600',      5],
          ['600',      4],
          ['600',      3],
          ['600',      2]
        ]);

        var options = {
          title: '%',
          curveType: 'function',
          legend: { position: 'bottom' },
	    colors: ['#0000FF'],
        };

        var chart = new google.visualization.LineChart(document.getElementById('curve_chart_vert'));

        chart.draw(data, options);
      }


// increase econ growth
      
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Quantity', 'Old Demand', 'New Demand', 'Supply'],
          ['500',  5, 6,     2],
          ['600',  4, 5,     3],
          ['700',  3, 4,     4],
          ['800',  2, 3,     5]
        ]);

        var options = {
          title: '%',
          curveType: 'function',
          legend: { position: 'bottom' },
	  series: {
            1: { lineDashStyle: [1, 1] },
	    },
	    colors: ['#0000FF', '#0000FF', '#ff0000'],
        };

        var chart = new google.visualization.LineChart(document.getElementById('curve_chart'));

        chart.draw(data, options);
      }


// infltion increase

            function drawChart2() {
        var data = google.visualization.arrayToDataTable([
          ['Quantity', 'Old Demand', 'New Demand', 'Old Supply', 'New Supply'],
          ['500',  5,  6,    2, 3],
          ['600',  4,  5,    3, 4],
          ['700',  3,  4,    4, 5],
          ['800',  2,  3,    5, 6]
        ]);

        var options = {
          title: '%',
          curveType: 'function',
          legend: { position: 'bottom' },
	  series: {
            1: { lineDashStyle: [1, 1] },
            3: { lineDashStyle: [1, 1] },
	    },
	    colors: ['#0000FF', '#0000FF', '#ff0000', '#ff0000'],
        };

        var chart = new google.visualization.LineChart(document.getElementById('curve_chart2'));

        chart.draw(data, options);
      }

    </script>
  </head>
#+end_export



In these notes we'll discuss the factors affecting the supply and demand for loanable funds.  Understanding these factors will give you a framework within which you can understand changes in equilibrium interest rates.

Before we jump in, however, you may want to take a look at the following video to understand what we mean by /equilibrium/ and in what sense it may be used.

#+begin_export html
<iframe width="560" height="315" src="https://www.youtube.com/embed/FveAr7T9fY0?si=kmkn_FOXU1PsFS-k" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
#+end_export


* Supply of Loanable Funds

Loanable funds are supplied primarily by (1) households, and also by (2) government and (3) businesses.  Note, funds are not supplied by banks---banks are merely the /intermediaries/.

#+begin_export html
<div id="curve_chart3"></div>
#+end_export

The supply curve for loanable funds is increasing.  This means as interest rates increase (the price of these funds), more funds are offered for loans.  This is analogous to more copper (or any asset) being offered for sale if the copper price is higher.

** Households

Households supply loanable funds through bank deposits and CD purchases.  Also, foreign households can supply loanable funds in the US market by purchasing securities (including US Treasury securities).  Households are a net supplier of funds.

** Businesses

Businesses may supply funds, however they are net demanders of funds.

** Governments

While certain part of the US government may supply funds, the US government is a net demander of funds due to its fiscal policy of spending much more than the tax revenues it collects. 

** The Federal Reserve

We will dedicate an entire set of lecture notes to the Fed later, however here we will note the Fed has a massive effect on the supply of loanable funds.  The Fed can create money through asset purchases, and therefore can at any point provide as much loanable funds to US markets as they wish.  Note, the Fed is not part of the US government.

* Demand of Loanable Funds

The demand curve is downwards sloping because less funds are demanded when the price of these funds (the interest rate) is higher.

#+begin_export html
<div id="curve_chart4"></div>
#+end_export

** Household Demand

Households demand funds for houses (mortgages), auto loans, and general spending (revolving loans). Generally thier demand for loanable funds increases over time with inflation and increasing wages.

** Business Demand

Businesses use decision rules such as Net Present Value and Internal Rate of Return to decide whether to make a capital investment. These rules are more likely to accept a project if the interest rate is lower, and therefore businesses demand more funds at lower interest rates.

Taxes may also have a large effect on business demand for loanable funds.  If corporate taxes decline then cash flows increase and business demand for funds will shift right.  /Shift right/ means more funds are demanded at every interest rate.

** Government Demand

Government demand for loanable funds is unique in that it generally doesn't depend on the interest rate. Governments demand the same amount of funds regardless of the interest rate.  We can represent this with a vertical demand curve. 


#+begin_comment
#+begin_export html
<div id="curve_chart_vert"></div>
#+end_export
#+end_comment

* Macroeconomic Factors that Shift the Equilibrium Interest Rate

In this section we will take a look at how the supply and demand for loanable funds will react to changes in macroeconomic variables. This will tell us the effect on the equilibrium interest rate.

** Economic Growth

*** An Increase in Economic Growth

An increase in economic growth will increase the demand for loanable funds---funds are needed for capital expansion.  The supply of loanable funds will generally remain unchanged.  This means interest rates will increase with increasing economic growth.

#+begin_export html
<div id="curve_chart"></div>
#+end_export

*** An Decrease in Economic Growth

Conversely, a decrease in economic growth will decrease the demand for loanable funds and leave the supply unchanged, thereby lowering interest rates.

#+begin_quote
**Passive Monetary Policy**: Note the Federal Reserve lowers interest rates when economic growth slows and raises interest rates when economic growth increases such that it causes inflation. But from what we just learned, we don't need the Fed to do this---interest rates will adjust by themselves.  The Fed will counter that they will increase and decrease interest rates /before/ the economic slowdown (or inflation) thereby keeping economic growth constant.  However a problem with this assertion (besides the Fed's track record) is you would need to be able to forecast economic growth which is a very difficult task.  
#+end_quote

** Inflation 

We may already be somewhat familiar with the relationship between inflation and nominal interest rates from the Fisher Effect:

$$(1 + n) = (1 + r)(1 + i)$$

where:

- n: the nominal interest rate
- r: the real interest rate
- i: expected inflation

#+begin_quote
-  Nominal Interest Rate:  the change in the amount of dollars you will have.
-  Real Interest Rate:  the change in the amount of stuff you will be able to buy
Note: we care about the real rate.
#+end_quote

From this equation we can see that as inflation increases, the nominal interest rate increases.  Nominal interest rates and inflation are positively related.

*** Increase in Inflation

Supply decreases and demand increases causing an increase in the equilibrium interest rate.

#+begin_export html
<div id="curve_chart2"></div>
#+end_export

See the video below for an explanation of the change in the equilibrium interest rate.

#+begin_export html
<iframe width="560" height="315" src="https://www.youtube.com/embed/JAe5dE619dA?si=XQb0Mb2TnVncpex8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
#+end_export

A decrease in inflation expectations will have the opposite effects on supply and demand, and thereby lower the equilibrium interest rate.

*** Increase in US Debt

The US government generally runs budget deficits and has a massive amount of outstanding debt.   This means as the government demands more funds, the demand curve shifts right, while the supply curve is unchanged.  This means the interest rate increases.

Remember the shape of the curve of the government demand for loanable funds---it is vertical meaning the government demands funds regardless of the interest rate. This means the government may demand so much funds that it increases interest rates beyond what businesses can pay.  This is called /crowding out/.

#+begin_quote
**A History of Crowding Out**:  Politicians like to spend, and so they have a history of downplaying the effect of government borrowing on interest rates.  For example, a recent Vice President was famous for stating "Deficits don't matter".
#+end_quote

From approximately 2000 to 2021 the US ran increasingly large deficits (as you can see in the charts below), however interest rates generally fell.  This is because while the US increased it debt, the Fed also increased the money supply (chart below).   The Fed essentially financed much of the US deficits with new money.  Foreigners also financed part of the deficits.  This works so long as inflation remains low, however inflation markedly increased around 2022, so the Fed may no longer be able to finance deficit spending.




#+caption: Total US Debt in $.  
#+begin_export html
<iframe src="https://fred.stlouisfed.org/graph/graph-landing.php?g=1cSNC&width=670&height=475" scrolling="no" frameborder="0" style="overflow:hidden; width:670px; height:525px;" allowTransparency="true" loading="lazy"></iframe>
#+end_export


#+caption: Total US Debt as a percent of US GDP. 
#+begin_export html
<iframe src="https://fred.stlouisfed.org/graph/graph-landing.php?g=1dsBt&width=670&height=475" scrolling="no" frameborder="0" style="overflow:hidden; width:670px; height:525px;" allowTransparency="true" loading="lazy"></iframe>
#+end_export

#+begin_export html
<iframe src="https://fred.stlouisfed.org/graph/graph-landing.php?g=1aBRl&width=670&height=475" scrolling="no" frameborder="0" style="overflow:hidden; width:670px; height:525px;" allowTransparency="true" loading="lazy"></iframe>
#+end_export

#+begin_export html
<iframe src="https://fred.stlouisfed.org/graph/graph-landing.php?g=1ep1G&width=670&height=475" scrolling="no" frameborder="0" style="overflow:hidden; width:670px; height:525px;" allowTransparency="true" loading="lazy"></iframe>
#+end_export


#+begin_export html
<iframe src="https://fred.stlouisfed.org/graph/graph-landing.php?g=1epHK&width=670&height=475" scrolling="no" frameborder="0" style="overflow:hidden; width:670px; height:525px;" allowTransparency="true" loading="lazy"></iframe>
#+end_export


*** Foreign Flows

Foreign investors may supply funds to US markets which will increase the supply curve and lower interest rates.  Of course, they can also demand funds in the US which will increase US interest rates.

Generally, however, foreigners have supplied funds to US markets as a result of the US trade deficit. We in the US buy more goods from abroad then we sell.  This means we send more US dollars abroad then foreign currency is sent to the US.  This would mean the US dollar would decline. So this doesn't happen (foreigners want the US dollar to be high---can you think of why?) they supply funds to US markets. In short, if you buy a $100 phone from abroad, foreigners then invest $100 in US markets (see the Balance of Payments for more).  So foreign flows have generally /lowered/ US interest rates.

* Conclusion

Changes in interest rates are the aggregation of all these factors. So if interest rates rise by a percent over the next month, we know in aggregate demand for funds increased more than supply, however the exact contribution of the budget deficit, or economic growth, etc is unclear.  We use statistical models to parse the various factors.

**A practical note on interest rate forecasting**

Forecasting interest rates is exceedingly difficult , and if you could do it you would be a billionaire trading your own account.  So most corporations who use interest rate forecasts just buy these forecasts from reputable investment banks.  In this way they don't waste money trying to do it themselves, and if they are wrong they can say they bought the forecast from the most knowledgeable people around (this is termed /CYA/ and as a practical matter drives many decisions). 


